#!/usr/bin/env bash
# Update package list and install Apache
apt-get update
apt-get install -y apache2

# Create HTML file with desired content
echo "Hello Holberton" > /var/www/html/index.html

# Restart Apache service
service apache2 restart
